language: node_js
node_js:
- '14'
cache:
  directories:
  - node_modules
script:
- yarn test
deploy:
  provider: heroku
  api_key:
    secure: qVzkx3RB7lBuhkv3+JWvJwH6nr5BCvg1PqcCBIMJwyd+l6qY+Gdm5uPgxuGysy5L/bDFfl63EyASwLoYpeAC6Jn4f4eiYcHr5mcHNOImUN8hwp7WyuxAD7I8Tkm2VjnZ30PmQvJlzB08294KTwZMbC4RMtKhTH8B/LDf/t/iz1sJYmrMf2gYAQp7/u+JvDi9r7pgBXuByNyUl+u9+ZfF6co6q38ex9UJOUQcntgZfCZuvOjLjoSU1cBcDRWAe3TcRmr4rMgi830ThkvCNCH2azYY91EgPJapQyUnhZ3XrkAG+3h4dz448Ix1Y+8Wi0roUGp5yDNYdYNfmALG0vUpoYTHx3oeKZH+aKj7qnyRuG1P+vO8rFEVd6NxCKt7XvWBTetpDpyW+iHNBQA7seM1S4z9utBYBX+J/ZXu4+jzX8z3VhioauGr2xnUB/zbAvcgpTH0O6tHOBQAS0tzpN+nq3+O31klgd6mxwFHGswDTPSpRkmB4BBfpNBdgQvpQjjrkmTOtr9RS3edgZGawsZVy6t/WFm72mzxi764K+8r87v05GMYjoIr8nPqap04gStttJXzHi2ncfxF1C0GtPIACyOldDu17HVB3T8CfawnFkM9JVBsi37Llpk1gl9f0lQ3HuZflgW9TiTYwOU2qECiGyfxth/3NfCuBt/cMQ7FbkY=
  app: lifeapp-server
  on:
    branch: master
