language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - yarn test

deploy:
  provider: heroku
  api_key:
    secure: DkObiosGkkAduBI/cx6VIW0l44eL3BgQxq5B6Tf08JIC6CleBeze5mGOXbQaOSyaBBZxK02ICDUw+v+k1I1KvhO92VmLjPLV/LNz7bVO3hHk/E9J9I6aNxpZJynxMxVRXkiCGaYgwEKj5TEYjeYmRhcyZcN3nFUTaBEkkx9KXQSmahucp6PxkqwxYxhmSHNy9j4ZUHv1zyo9mwIXty2I4J93bbrQfqbxo07456TK6kl1nfW+6RtJBGfyOZIisfgsFCTnOeBpoJN9MDhN2Gq/BuWvDmeeKReqzGDby8Y5M1cXV2D58KgmYe/UNeJ2uOAOh9fiBDG1W8y7/gd5kZheMmqMVONf/orbUjPs0AjHya7T0ot0cSP6qEHE3xzo9Acd3BEsU+ObEri066Wz91ISN9IB5CI5WRfX3+xXXfDCSo5em24MWeHEWEKcsPGS4HCfezFwW/Q1vLK86x0s2cgmMJaNQb0kN3DVvUwUWKDls+2eY0tn2If+eV/ZaXtg8g0PPuTcobqI89T3Pj5KgSxs0bxi7f/yP+LhMHxeJBCsp4/pnrFUK9JK7eFJGQA4Ms1F7LdD7F16qUOQ13czUrRHm1LzijKcqbMrV2OESQlKKqrFO2lyjBvv91BMpwyigzaaM83LgjTZW5tkI7XFKPuHIDJbCdUB96R+iuqxnq8uCL8=
  app: lifeapp-server
  on:
    branch: master
