import { TASK_TYPE_VALUE_MAP } from '../../../constants';
import { Field } from '../../interfaces';
import { FIELDS_CONFIG } from './fieldsConfig';

export const TASK_FIELDS: TASK_TYPE_VALUE_MAP<Array<Partial<Field>>> = {
  EVENT: [
    FIELDS_CONFIG.TITLE,
    FIELDS_CONFIG.PRIORITY,
    FIELDS_CONFIG.STATUS,
    FIELDS_CONFIG.NOTE,
    FIELDS_CONFIG.LOCATION,
    FIELDS_CONFIG.DATE,
    FIELDS_CONFIG.DURATION,
    FIELDS_CONFIG.NOTIFICATIONS,
  ],
  GOAL: [
    FIELDS_CONFIG.TITLE,
    FIELDS_CONFIG.PRIORITY,
    FIELDS_CONFIG.STATUS,
    FIELDS_CONFIG.PROGRESS,
    FIELDS_CONFIG.NOTIFICATIONS,
  ],
  MEETING: [
    FIELDS_CONFIG.TITLE,
    FIELDS_CONFIG.PRIORITY,
    FIELDS_CONFIG.STATUS,
    FIELDS_CONFIG.NOTE,
    FIELDS_CONFIG.LOCATION,
    FIELDS_CONFIG.DATE_TIME,
    FIELDS_CONFIG.DURATION,
    FIELDS_CONFIG.PERSON,
    FIELDS_CONFIG.NOTIFICATIONS,
  ],
  ROUTINE: [
    FIELDS_CONFIG.TITLE,
    FIELDS_CONFIG.PRIORITY,
    FIELDS_CONFIG.STATUS,
    FIELDS_CONFIG.CYCLE,
    FIELDS_CONFIG.ACTION,
    FIELDS_CONFIG.NOTIFICATIONS,
  ],
  TODO: [
    FIELDS_CONFIG.TITLE,
    FIELDS_CONFIG.PRIORITY,
    FIELDS_CONFIG.STATUS,
    FIELDS_CONFIG.NOTE,
    FIELDS_CONFIG.NOTIFICATIONS,
  ],
};
